#!/bin/bash

set -e



# change ownership
echo "Change directory ownership"
sudo chown -R ubuntu:ubuntu /opt/wetribe/


# make writeable for php
DIR_WRITE_ROOT=/etc/wetribe/data
mkdir -p "${DIR_WRITE_ROOT}"

declare -a CACHE_FOLDERS=( \
    'bootstrap' \
    'bootstrap/cache' \
    'public' \
    'public/temp' \
    'storage' \
    'storage/app' \
    'storage/app/public' \
    'storage/framework' \
    'storage/framework/cache' \
    'storage/framework/cache/data' \
    'storage/framework/sessions' \
    'storage/framework/testing' \
    'storage/framework/views' \
    'storage/js-daemon/' \
    'storage/js-daemon/tmp-upload' \
    'upload' \
)

# cleanup cache because old code may effect to with old code
rm -rf "${DIR_WRITE_ROOT}/bootstrap"
rm -rf "${DIR_WRITE_ROOT}/storage"

for folder in ${CACHE_FOLDERS[@]}; do
    tmp_folder="${DIR_WRITE_ROOT}/${folder}"
    if [ -d "${tmp_folder}" ]; then
      :
    else
      echo "create folder: ${tmp_folder}"
      mkdir -p "${tmp_folder}"
    fi
done

sudo chmod -R 777 "${DIR_WRITE_ROOT}"
sudo chown -R www-data:www-data "${DIR_WRITE_ROOT}"


sudo pm2 restart /opt/wetribe/source/js-app/app.prod.config.js
sudo systemctl restart nginx
sudo systemctl restart php7.4-fpm



echo "*************************************"
echo "**** DONE. Please do xxxxx ****"
echo "*************************************"
