#!/bin/bash

set -e



# change ownership
echo "Change directory ownership"
sudo chown -R ubuntu:ubuntu /opt/redletter/


# make writeable for php
DIR_WRITE_ROOT=/etc/redletter/data
mkdir -p "${DIR_WRITE_ROOT}"

declare -a CACHE_FOLDERS=( \
    'public' \
    'public/temp' \
    'upload' \
)

for folder in ${CACHE_FOLDERS[@]}; do
    tmp_folder="${DIR_WRITE_ROOT}/${folder}"
    if [ -d "${tmp_folder}" ]; then
      :
    else
      echo "create folder: ${tmp_folder}"
      mkdir -p "${tmp_folder}"
    fi
done

sudo chmod -R 777 "${DIR_WRITE_ROOT}"
sudo chown -R www-data:www-data "${DIR_WRITE_ROOT}"

# First time only
# sudo pm2 start /opt/redletter/source/backend-bundle/app.prod.config.js 
sudo pm2 restart /opt/redletter/source/backend-bundle/app.prod.config.js
sudo systemctl restart nginx

echo "*************************************"
echo "**** DONE. Please do xxxxx ****"
echo "*************************************"
